# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名

version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    privileged: true
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql80
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: xiaomurui
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - my-network
  mysql:
    image: mysql:8.0.32
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - my-network
    ports:
      - "23306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s

networks:
  my-network:
    driver: bridge

